# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postolka_res_system
    username: appUser
    password: postolka_DB
  jpa:
    hibernate:
      ddl-auto: update


# Security configuration
#  security:
#    user:
#      name: user
#      password: pass


#JWT token configuration
jwt:
  secret: hokrko
  expiration: 3600000



